name: Build

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  # Build image
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [mamba, conda]
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build Image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./images/base/dockerfile"
          context: "./images/base/"
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterstack:${{ matrix.mamba }}-base
          build-args: |
            IMAGE_TAG=${{ matrix.mamba }}
      - 
        name: Update docker description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterstack
  #
  build-cuda-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [mamba, conda]
        cuda_runtime: [runtime, devel]
        cuda_version: [112, 113, 114, 115, 116, 117, 118]
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        run: |
          IMAGE_TAG=${{ matrix.mamba }}-cu${{ matrix.cuda_version }}
          # -------------------------------------------
          # Prepare runtime tag.
          # -------------------------------------------
          if [ "${{ matrix.cuda_runtime }}" == "devel" ]; then
            IMAGE_TAG=${IMAGE_TAG}-${{ matrix.cuda_runtime }}
          fi
          # -------------------------------------------
          # Prepare image tags.
          # -------------------------------------------
          IMAGE_TAG=${{ matrix.mamba }}
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV
      - 
        name: Build Image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./images/base/dockerfile"
          context: "./images/base/"
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jupyterstack:${{ env.image_tag }}-base
          build-args: |
            IMAGE_TAG=${{ env.image_tag }}